apiVersion: v1
kind: Config
clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 #pour le moment mettre 192.168.21.100
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3SGhjTk1qWXdNekkyTWpBek5URTFXaGNOTXpZd016SXpNakF6TlRFMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ2tIaU1memtTVEI5RWZ6WWVRSzNhMjA1NytRSVFacGxhdGpiZmZlUWIKYytuK2FGc3hnWmI3ckFiRlR4WU40cnN4MlRJRVVKcFExQVlicmtYRHdad1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlkUXl6RmVsTHAwSzBHZDAzdnNSCmVIUmp1dWt3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQXB2bFRSMkorWkFmRXJzK2wzWHZZbjREckliV1V5dzAKWjlocGFUT1llVUVDSUU3WlhLOGZIRm44OWlRSkpIenF6T2YyUm81NU1rV09rZkZqTkVMRUZhQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc1NDM4ODEyLCJpYXQiOjE3NzU0MzUyMTIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOTYyMzQzZGEtNzVjNS00MzNkLTliNDctNjhiNTY2MWYzZjYwIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6IjNmOTVhMGI4LTgwZjYtNGNjYi1hMzI3LThlYjg2MjY4ZTM0YSJ9fSwibmJmIjoxNzc1NDM1MjEyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.f8WWFV__ULnxKa9qNEckt5GxMl4xVUN86lvRgcYqmFn-G_bzRCIBaN0vw3ZEKzFJdq3_feI4dXrKkBeYNqJIILyFHJkbrQIdOYDqCIK0Tt99DpXxrVwwEEuAqikdvJVxWyX_IUBJKvXBDOI8d6lMC8qrCJ4972JxInNJxOFrCebmntMC_NtINtDq_q3YOsfD33VfyIZdG2hkNzXOCY3MHvnUdpRGA12yE6pH2IQFJyGoLbdIb7j-4dBzGfrpHW4LBXoQbuNSTqfFBCx2xJQzJgbm1zqS0WvXgR2Rju5cNi8nu6J_VvL_nf2_cNBX2-mer8REixdphiINTzrK24Y5dQ
contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev
current-context: etudiant-context